[plugin]
repository = "https://github.com/Blackcatz1911/CurrencySpender.git"
owners = ["Blackcatz1911"]
project_path = "CurrencySpender"
commit = "eda7f945c615186f2408af2f44a4ef95f1ad138f"
changelog = """
## 1.2.3
### Added
- A new setting to automatically open Currency Spender together with the Currency window.
- A new button on the Currency window.
### Fixed
- Incorrect check for Framer's Kits has been resolved.
### Changed
- ECommons is now used as a NuGet package.
"""
version = "1.2.3"
